--Cleaning
USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.STAGING;

--CHARTEVENTS
CREATE OR REPLACE TABLE CHARTEVENTS_CLEAN AS
SELECT
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    ICUSTAY_ID,                   -- May be NULL for non ICU events
    ITEMID,
    CHARTTIME,
    STORETIME,
    CGID,
    TRIM(VALUE) AS VALUE,         -- trim spaces
    VALUENUM,                     -- numeric
    TRIM(VALUEUOM) AS VALUEUOM,   -- trim spaces
    WARNING,
    ERROR,
    UPPER(TRIM(RESULTSTATUS)) AS RESULTSTATUS,  -- standardize text
    UPPER(TRIM(STOPPED)) AS STOPPED             -- standardize text
FROM GRP5_ASG.RAW.CHARTEVENTS
-- Keep only valid rows for analysis
WHERE ROW_ID IS NOT NULL
  AND SUBJECT_ID IS NOT NULL
  AND HADM_ID IS NOT NULL

SELECT 
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN ICUSTAY_ID IS NULL THEN 1 ELSE 0 END) AS icustay_id_nulls
FROM CHARTEVENTS_CLEAN;

SELECT
    SUM(CASE WHEN VALUE IS NOT NULL AND VALUE <> TRIM(VALUE) THEN 1 ELSE 0 END) AS value_needs_trim,
    SUM(CASE WHEN VALUEUOM IS NOT NULL AND VALUEUOM <> TRIM(VALUEUOM) THEN 1 ELSE 0 END) AS valueuom_needs_trim,
    SUM(CASE WHEN RESULTSTATUS IS NOT NULL AND RESULTSTATUS <> TRIM(RESULTSTATUS) THEN 1 ELSE 0 END) AS resultstatus_needs_trim,
    SUM(CASE WHEN STOPPED IS NOT NULL AND STOPPED <> TRIM(STOPPED) THEN 1 ELSE 0 END) AS stopped_needs_trim
FROM CHARTEVENTS_CLEAN;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ICUSTAY_ID) AS unique_icu_stays
FROM CHARTEVENTS_CLEAN;

SELECT *
FROM STAGING.CHARTEVENTS_CLEAN
LIMIT 10;

--DIAGNOSES_ICD
CREATE OR REPLACE TABLE DIAGNOSES_ICD_CLEAN AS
SELECT 
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    SEQ_NUM,
    UPPER(TRIM(ICD9_CODE)) AS ICD9_CODE
FROM GRP5_ASG.RAW.DIAGNOSES_ICD;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_id,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,

    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS icd9_code_nulls,
    
    SUM(CASE WHEN ICD9_CODE IS NOT NULL AND ICD9_CODE <> TRIM(ICD9_CODE) THEN 1 ELSE 0 END) AS icd9_codes_trim
FROM DIAGNOSES_ICD_CLEAN;

SELECT *
FROM STAGING.DIAGNOSES_ICD_CLEAN;

--SERVICES
CREATE OR REPLACE TABLE STAGING.SERVICES_CLEAN AS
SELECT
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    TRANSFERTIME,
    UPPER(TRIM(PREV_SERVICE)) AS PREV_SERVICE,  --Standardize text
    UPPER(TRIM(CURR_SERVICE)) AS CURR_SERVICE   --Standardize text
FROM GRP5_ASG.RAW.SERVICES;

SELECT
    (SELECT COUNT(*) FROM GRP5_ASG.RAW.SERVICES) AS original_count,
    (SELECT COUNT(*) FROM STAGING.SERVICES_CLEAN) AS cleaned_count;

SELECT 
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls
FROM STAGING.SERVICES_CLEAN;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ROW_ID) AS unique_rows,
    SUM(CASE WHEN PREV_SERVICE IS NOT NULL AND PREV_SERVICE <> TRIM(PREV_SERVICE) THEN 1 ELSE 0 END) AS prev_service_needs_trim,
    SUM(CASE WHEN CURR_SERVICE IS NOT NULL AND CURR_SERVICE <> TRIM(CURR_SERVICE) THEN 1 ELSE 0 END) AS curr_service_needs_trim
FROM STAGING.SERVICES_CLEAN;

SELECT *
FROM STAGING.SERVICES_CLEAN
LIMIT 10;

--Upload tables to clean schema
USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.CLEAN;

CREATE OR REPLACE TABLE CHARTEVENTS AS
SELECT *
FROM GRP5_ASG.STAGING.CHARTEVENTS_CLEAN;

CREATE OR REPLACE TABLE DIAGNOSES_ICD AS
SELECT *
FROM GRP5_ASG.STAGING.DIAGNOSES_ICD_CLEAN;

CREATE OR REPLACE TABLE SERVICES AS
SELECT *
FROM GRP5_ASG.STAGING.SERVICES_CLEAN;