USE DATABASE GRP5_ASG;
USE SCHEMA ANALYTICS;


USE ROLE sysadmin;
CREATE ROLE ADMIN_ROLE;
CREATE ROLE ANALYST_ROLE;

GRANT USAGE ON DATABASE GRP5_ASG TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA GRP5_ASG.ANALYTICS TO ROLE ANALYST_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA GRP5_ASG.ANALYTICS TO ROLE ANALYST_ROLE;

CREATE OR REPLACE MASKING POLICY mask_num38
AS (val NUMBER(38,0))
RETURNS NUMBER(38,0) ->
  CASE
    WHEN CURRENT_ROLE() = 'ADMIN_ROLE' THEN val
    ELSE NULL
  END;

CREATE OR REPLACE MASKING POLICY mask_num15_6
AS (val NUMBER(15,6))
RETURNS NUMBER(15,6) ->
  CASE
    WHEN CURRENT_ROLE() = 'ADMIN_ROLE' THEN val
    ELSE NULL
  END;

CREATE OR REPLACE MASKING POLICY mask_varchar
AS (val STRING)
RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() = 'ADMIN_ROLE' THEN val
    ELSE 'REDACTED'
  END;

-- IDs
ALTER TABLE GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
  MODIFY COLUMN SUBJECT_ID
  SET MASKING POLICY mask_num38;

ALTER TABLE GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
  MODIFY COLUMN HADM_ID
  SET MASKING POLICY mask_num38;

-- Sensitive demographics/coverage
ALTER TABLE GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
  MODIFY COLUMN ETHNICITY
  SET MASKING POLICY mask_varchar;

ALTER TABLE GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
  MODIFY COLUMN INSURANCE
  SET MSKING POLICY mask_varchar;

USE ROLE SYSADMIN;

SELECT SUBJECT_ID, HADM_ID, INSURANCE, ETHNICITY, ADMIT_DATE, DISCH_DATE
FROM GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
LIMIT 10;

USE ROLE ANALYST_ROLE;

SELECT SUBJECT_ID, HADM_ID, INSURANCE, ETHNICITY, ADMIT_DATE, DISCH_DATE
FROM GRP5_ASG.ANALYTICS.FACT_ADMISSIONS
LIMIT 10;

GRANT ROLE ANALYST_ROLE TO USER BISON
GRANT ROLE ANALYST_ROLE TO USER BOA
GRANT ROLE ANALYST_ROLE TO USER FOX
GRANT ROLE ANALYST_ROLE TO USER BULLFROG
GRANT ROLE ANALYST_ROLE TO USER CHIPMUNK
