USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.RAW;

--DIAGNOSES_ICD
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_ids,
    COUNT(DISTINCT SUBJECT_ID) AS distinct_patients,
    COUNT(DISTINCT HADM_ID) AS distinct_admissions,
    COUNT(DISTINCT ICD9_CODE) AS distinct_icd9_codes
FROM DIAGNOSES_ICD;

WITH dupes AS (
    SELECT SUBJECT_ID, HADM_ID, SEQ_NUM, COUNT(*) AS cnt
    FROM GRP5_ASG.RAW.DIAGNOSES_ICD
    GROUP BY SUBJECT_ID, HADM_ID, SEQ_NUM
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.DIAGNOSES_ICD d
WHERE EXISTS (
    SELECT 1
    FROM dupes x
    WHERE x.SUBJECT_ID = d.SUBJECT_ID
      AND x.HADM_ID = d.HADM_ID
      AND x.SEQ_NUM = d.SEQ_NUM
);

SELECT ROW_ID, COUNT(*) AS cnt
FROM DIAGNOSES_ICD
GROUP BY ROW_ID
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS null_row_ids
FROM DIAGNOSES_ICD
WHERE ROW_ID IS NULL;

SELECT HADM_ID, SEQ_NUM, COUNT(*) AS cnt
FROM DIAGNOSES_ICD
GROUP BY HADM_ID, SEQ_NUM
HAVING COUNT(*) > 1;

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN SEQ_NUM IS NULL THEN 1 ELSE 0 END) AS seq_num_nulls,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS icd9_code_nulls
FROM DIAGNOSES_ICD;

SELECT
    SUBJECT_ID,
    COUNT(DISTINCT HADM_ID) AS admissions_per_patient,
    COUNT(*) AS diagnoses_per_patient
FROM DIAGNOSES_ICD
GROUP BY SUBJECT_ID
ORDER BY diagnoses_per_patient DESC;

SELECT
    HADM_ID,
    COUNT(*) AS diagnoses_per_admission
FROM DIAGNOSES_ICD
GROUP BY HADM_ID
ORDER BY diagnoses_per_admission DESC;

SELECT COUNT(*) AS orphan_admissions
FROM DIAGNOSES_ICD d
LEFT JOIN ADMISSIONS a
ON d.HADM_ID = a.HADM_ID
WHERE a.HADM_ID IS NULL;

SELECT COUNT(*) AS orphan_icd_trimmed
FROM (
    SELECT TRIM(ICD9_CODE) AS ICD9_CODE_TRIM
    FROM DIAGNOSES_ICD
) d
LEFT JOIN DIAGNOSES i
ON d.ICD9_CODE_TRIM = i.ICD9_CODE
WHERE i.ICD9_CODE IS NULL;

--CHARTEVENTS
SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS unique_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ICUSTAY_ID) AS unique_icu_stays,
    COUNT(DISTINCT ITEMID) AS unique_items
FROM CHARTEVENTS;

WITH dupes AS (
    SELECT ROW_ID, COUNT(*)
    FROM GRP5_ASG.RAW.CHARTEVENTS
    GROUP BY ROW_ID
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.CHARTEVENTS c
WHERE EXISTS (
    SELECT 1
    FROM dupes d
    WHERE d.ROW_ID = c.ROW_ID
);

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS null_subject_id,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS null_hadm_id,
    SUM(CASE WHEN ICUSTAY_ID IS NULL THEN 1 ELSE 0 END) AS null_icustay_id,
    SUM(CASE WHEN ITEMID IS NULL THEN 1 ELSE 0 END) AS null_itemid,
    SUM(CASE WHEN CHARTTIME IS NULL THEN 1 ELSE 0 END) AS null_charttime,
    SUM(CASE WHEN STORETIME IS NULL THEN 1 ELSE 0 END) AS null_storetime,
    SUM(CASE WHEN CGID IS NULL THEN 1 ELSE 0 END) AS null_cgid,
    SUM(CASE WHEN VALUE IS NULL THEN 1 ELSE 0 END) AS null_value,
    SUM(CASE WHEN VALUENUM IS NULL THEN 1 ELSE 0 END) AS null_valuenum,
    SUM(CASE WHEN VALUEUOM IS NULL THEN 1 ELSE 0 END) AS null_valueuom,
    SUM(CASE WHEN WARNING IS NULL THEN 1 ELSE 0 END) AS null_warning,
    SUM(CASE WHEN ERROR IS NULL THEN 1 ELSE 0 END) AS null_error,
    SUM(CASE WHEN RESULTSTATUS IS NULL THEN 1 ELSE 0 END) AS null_resultstatus,
    SUM(CASE WHEN STOPPED IS NULL THEN 1 ELSE 0 END) AS null_stopped
FROM CHARTEVENTS;

SELECT
    CASE WHEN COUNT(*) = COUNT(DISTINCT ROW_ID) THEN 'ROW_ID is unique' ELSE 'ROW_ID has duplicates' END AS row_id_check
FROM CHARTEVENTS;

-- 4. Orphan foreign keys check
-- a) HADM_ID not in ADMISSIONS
SELECT COUNT(*) AS orphan_hadm
FROM CHARTEVENTS c
LEFT JOIN ADMISSIONS a
ON c.HADM_ID = a.HADM_ID
WHERE c.HADM_ID IS NOT NULL AND a.HADM_ID IS NULL;

-- b) ICUSTAY_ID not in ICUSTAYS
SELECT COUNT(*) AS orphan_icustay
FROM CHARTEVENTS c
LEFT JOIN ICUSTAYS i
ON c.ICUSTAY_ID = i.ICUSTAY_ID
WHERE c.ICUSTAY_ID IS NOT NULL AND i.ICUSTAY_ID IS NULL;

-- c) SUBJECT_ID not in PATIENTS
SELECT COUNT(*) AS orphan_subject
FROM CHARTEVENTS c
LEFT JOIN PATIENTS p
ON c.SUBJECT_ID = p.SUBJECT_ID
WHERE p.SUBJECT_ID IS NULL;

-- 5. Summary statistics for VALUENUM
SELECT 
    MIN(VALUENUM) AS min_value,
    MAX(VALUENUM) AS max_value,
    AVG(VALUENUM) AS avg_value,
    STDDEV(VALUENUM) AS stddev_value
FROM CHARTEVENTS
WHERE VALUENUM IS NOT NULL;

--SERVICES
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_id,
    COUNT(DISTINCT SUBJECT_ID) AS distinct_subject_id,
    COUNT(DISTINCT HADM_ID) AS distinct_hadm_id,
    COUNT(DISTINCT TRANSFERTIME) AS distinct_transfertime,
    COUNT(DISTINCT PREV_SERVICE) AS distinct_prev_service,
    COUNT(DISTINCT CURR_SERVICE) AS distinct_curr_service
FROM SERVICES;

WITH dupes AS (
    SELECT ROW_ID, COUNT(*)
    FROM GRP5_ASG.RAW.SERVICES
    GROUP BY ROW_ID
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.SERVICES s
WHERE EXISTS (
    SELECT 1
    FROM dupes d
    WHERE d.ROW_ID = s.ROW_ID
);
SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS null_subject_id,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS null_hadm_id,
    SUM(CASE WHEN TRANSFERTIME IS NULL THEN 1 ELSE 0 END) AS null_transfertime,
    SUM(CASE WHEN PREV_SERVICE IS NULL THEN 1 ELSE 0 END) AS null_prev_service,
    SUM(CASE WHEN CURR_SERVICE IS NULL THEN 1 ELSE 0 END) AS null_curr_service
FROM SERVICES;

SELECT ROW_ID, COUNT(*) AS count
FROM SERVICES
GROUP BY ROW_ID
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS null_row_id
FROM SERVICES
WHERE ROW_ID IS NULL;

-- a) SUBJECT_ID not in PATIENTS
SELECT COUNT(*) AS orphan_subject
FROM SERVICES s
LEFT JOIN PATIENTS p
ON s.SUBJECT_ID = p.SUBJECT_ID
WHERE s.SUBJECT_ID IS NOT NULL AND p.SUBJECT_ID IS NULL;

-- b) HADM_ID not in ADMISSIONS
SELECT COUNT(*) AS orphan_hadm
FROM SERVICES s
LEFT JOIN ADMISSIONS a
ON s.HADM_ID = a.HADM_ID
WHERE s.HADM_ID IS NOT NULL AND a.HADM_ID IS NULL;

SELECT HADM_ID, COUNT(*) AS service_count
FROM SERVICES
GROUP BY HADM_ID
ORDER BY service_count DESC;

--Cleaning
USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.STAGING;

--CHARTEVENTS
CREATE OR REPLACE TABLE CHARTEVENTS_CLEAN AS
SELECT
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    ICUSTAY_ID,                   -- May be NULL for non ICU events
    ITEMID,
    CHARTTIME,
    STORETIME,
    CGID,
    TRIM(VALUE) AS VALUE,         -- trim spaces
    VALUENUM,                     -- numeric
    TRIM(VALUEUOM) AS VALUEUOM,   -- trim spaces
    WARNING,
    ERROR,
    UPPER(TRIM(RESULTSTATUS)) AS RESULTSTATUS,  -- standardize text
    UPPER(TRIM(STOPPED)) AS STOPPED             -- standardize text
FROM GRP5_ASG.RAW.CHARTEVENTS
-- Keep only valid rows for analysis
WHERE ROW_ID IS NOT NULL
  AND SUBJECT_ID IS NOT NULL
  AND HADM_ID IS NOT NULL

SELECT 
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN ICUSTAY_ID IS NULL THEN 1 ELSE 0 END) AS icustay_id_nulls
FROM CHARTEVENTS_CLEAN;

SELECT
    SUM(CASE WHEN VALUE IS NOT NULL AND VALUE <> TRIM(VALUE) THEN 1 ELSE 0 END) AS value_needs_trim,
    SUM(CASE WHEN VALUEUOM IS NOT NULL AND VALUEUOM <> TRIM(VALUEUOM) THEN 1 ELSE 0 END) AS valueuom_needs_trim,
    SUM(CASE WHEN RESULTSTATUS IS NOT NULL AND RESULTSTATUS <> TRIM(RESULTSTATUS) THEN 1 ELSE 0 END) AS resultstatus_needs_trim,
    SUM(CASE WHEN STOPPED IS NOT NULL AND STOPPED <> TRIM(STOPPED) THEN 1 ELSE 0 END) AS stopped_needs_trim
FROM CHARTEVENTS_CLEAN;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ICUSTAY_ID) AS unique_icu_stays
FROM CHARTEVENTS_CLEAN;

SELECT *
FROM STAGING.CHARTEVENTS_CLEAN
LIMIT 10;

--DIAGNOSES_ICD
CREATE OR REPLACE TABLE DIAGNOSES_ICD_CLEAN AS
SELECT 
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    SEQ_NUM,
    UPPER(TRIM(ICD9_CODE)) AS ICD9_CODE
FROM GRP5_ASG.RAW.DIAGNOSES_ICD;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_id,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,

    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS icd9_code_nulls,
    
    SUM(CASE WHEN ICD9_CODE IS NOT NULL AND ICD9_CODE <> TRIM(ICD9_CODE) THEN 1 ELSE 0 END) AS icd9_codes_trim
FROM DIAGNOSES_ICD_CLEAN;

SELECT *
FROM STAGING.DIAGNOSES_ICD_CLEAN;

--SERVICES
CREATE OR REPLACE TABLE STAGING.SERVICES_CLEAN AS
SELECT
    ROW_ID,                       -- Primary key no nulls
    SUBJECT_ID,                   -- Foreign key to patients
    HADM_ID,                      -- Foreign key to admissions
    TRANSFERTIME,
    UPPER(TRIM(PREV_SERVICE)) AS PREV_SERVICE,  --Standardize text
    UPPER(TRIM(CURR_SERVICE)) AS CURR_SERVICE   --Standardize text
FROM GRP5_ASG.RAW.SERVICES;

SELECT
    (SELECT COUNT(*) FROM GRP5_ASG.RAW.SERVICES) AS original_count,
    (SELECT COUNT(*) FROM STAGING.SERVICES_CLEAN) AS cleaned_count;

SELECT 
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls
FROM STAGING.SERVICES_CLEAN;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ROW_ID) AS unique_rows,
    SUM(CASE WHEN PREV_SERVICE IS NOT NULL AND PREV_SERVICE <> TRIM(PREV_SERVICE) THEN 1 ELSE 0 END) AS prev_service_needs_trim,
    SUM(CASE WHEN CURR_SERVICE IS NOT NULL AND CURR_SERVICE <> TRIM(CURR_SERVICE) THEN 1 ELSE 0 END) AS curr_service_needs_trim
FROM STAGING.SERVICES_CLEAN;

SELECT *
FROM STAGING.SERVICES_CLEAN
LIMIT 10;

--Upload tables to clean schema
USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.CLEAN;

CREATE OR REPLACE TABLE CHARTEVENTS AS
SELECT *
FROM GRP5_ASG.STAGING.CHARTEVENTS_CLEAN;

CREATE OR REPLACE TABLE DIAGNOSES_ICD AS
SELECT *
FROM GRP5_ASG.STAGING.DIAGNOSES_ICD_CLEAN;

CREATE OR REPLACE TABLE SERVICES AS
SELECT *
FROM GRP5_ASG.STAGING.SERVICES_CLEAN;