USE ROLE TRAINING_ROLE;
USE WAREHOUSE BISON_WH;
USE DATABASE GRP5_ASG;
USE SCHEMA GRP5_ASG.RAW;

--DIAGNOSES_ICD
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_ids,
    COUNT(DISTINCT SUBJECT_ID) AS distinct_patients,
    COUNT(DISTINCT HADM_ID) AS distinct_admissions,
    COUNT(DISTINCT ICD9_CODE) AS distinct_icd9_codes
FROM DIAGNOSES_ICD;

WITH dupes AS (
    SELECT SUBJECT_ID, HADM_ID, SEQ_NUM, COUNT(*) AS cnt
    FROM GRP5_ASG.RAW.DIAGNOSES_ICD
    GROUP BY SUBJECT_ID, HADM_ID, SEQ_NUM
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.DIAGNOSES_ICD d
WHERE EXISTS (
    SELECT 1
    FROM dupes x
    WHERE x.SUBJECT_ID = d.SUBJECT_ID
      AND x.HADM_ID = d.HADM_ID
      AND x.SEQ_NUM = d.SEQ_NUM
);

SELECT ROW_ID, COUNT(*) AS cnt
FROM DIAGNOSES_ICD
GROUP BY ROW_ID
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS null_row_ids
FROM DIAGNOSES_ICD
WHERE ROW_ID IS NULL;

SELECT HADM_ID, SEQ_NUM, COUNT(*) AS cnt
FROM DIAGNOSES_ICD
GROUP BY HADM_ID, SEQ_NUM
HAVING COUNT(*) > 1;

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS row_id_nulls,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS subject_id_nulls,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS hadm_id_nulls,
    SUM(CASE WHEN SEQ_NUM IS NULL THEN 1 ELSE 0 END) AS seq_num_nulls,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS icd9_code_nulls
FROM DIAGNOSES_ICD;

SELECT
    SUBJECT_ID,
    COUNT(DISTINCT HADM_ID) AS admissions_per_patient,
    COUNT(*) AS diagnoses_per_patient
FROM DIAGNOSES_ICD
GROUP BY SUBJECT_ID
ORDER BY diagnoses_per_patient DESC;

SELECT
    HADM_ID,
    COUNT(*) AS diagnoses_per_admission
FROM DIAGNOSES_ICD
GROUP BY HADM_ID
ORDER BY diagnoses_per_admission DESC;

SELECT COUNT(*) AS orphan_admissions
FROM DIAGNOSES_ICD d
LEFT JOIN ADMISSIONS a
ON d.HADM_ID = a.HADM_ID
WHERE a.HADM_ID IS NULL;

SELECT COUNT(*) AS orphan_icd_trimmed
FROM (
    SELECT TRIM(ICD9_CODE) AS ICD9_CODE_TRIM
    FROM DIAGNOSES_ICD
) d
LEFT JOIN DIAGNOSES i
ON d.ICD9_CODE_TRIM = i.ICD9_CODE
WHERE i.ICD9_CODE IS NULL;

--CHARTEVENTS
SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS unique_rows,
    COUNT(DISTINCT SUBJECT_ID) AS unique_patients,
    COUNT(DISTINCT HADM_ID) AS unique_admissions,
    COUNT(DISTINCT ICUSTAY_ID) AS unique_icu_stays,
    COUNT(DISTINCT ITEMID) AS unique_items
FROM CHARTEVENTS;

WITH dupes AS (
    SELECT ROW_ID, COUNT(*)
    FROM GRP5_ASG.RAW.CHARTEVENTS
    GROUP BY ROW_ID
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.CHARTEVENTS c
WHERE EXISTS (
    SELECT 1
    FROM dupes d
    WHERE d.ROW_ID = c.ROW_ID
);

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS null_subject_id,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS null_hadm_id,
    SUM(CASE WHEN ICUSTAY_ID IS NULL THEN 1 ELSE 0 END) AS null_icustay_id,
    SUM(CASE WHEN ITEMID IS NULL THEN 1 ELSE 0 END) AS null_itemid,
    SUM(CASE WHEN CHARTTIME IS NULL THEN 1 ELSE 0 END) AS null_charttime,
    SUM(CASE WHEN STORETIME IS NULL THEN 1 ELSE 0 END) AS null_storetime,
    SUM(CASE WHEN CGID IS NULL THEN 1 ELSE 0 END) AS null_cgid,
    SUM(CASE WHEN VALUE IS NULL THEN 1 ELSE 0 END) AS null_value,
    SUM(CASE WHEN VALUENUM IS NULL THEN 1 ELSE 0 END) AS null_valuenum,
    SUM(CASE WHEN VALUEUOM IS NULL THEN 1 ELSE 0 END) AS null_valueuom,
    SUM(CASE WHEN WARNING IS NULL THEN 1 ELSE 0 END) AS null_warning,
    SUM(CASE WHEN ERROR IS NULL THEN 1 ELSE 0 END) AS null_error,
    SUM(CASE WHEN RESULTSTATUS IS NULL THEN 1 ELSE 0 END) AS null_resultstatus,
    SUM(CASE WHEN STOPPED IS NULL THEN 1 ELSE 0 END) AS null_stopped
FROM CHARTEVENTS;

SELECT
    CASE WHEN COUNT(*) = COUNT(DISTINCT ROW_ID) THEN 'ROW_ID is unique' ELSE 'ROW_ID has duplicates' END AS row_id_check
FROM CHARTEVENTS;

-- 4. Orphan foreign keys check
-- a) HADM_ID not in ADMISSIONS
SELECT COUNT(*) AS orphan_hadm
FROM CHARTEVENTS c
LEFT JOIN ADMISSIONS a
ON c.HADM_ID = a.HADM_ID
WHERE c.HADM_ID IS NOT NULL AND a.HADM_ID IS NULL;

-- b) ICUSTAY_ID not in ICUSTAYS
SELECT COUNT(*) AS orphan_icustay
FROM CHARTEVENTS c
LEFT JOIN ICUSTAYS i
ON c.ICUSTAY_ID = i.ICUSTAY_ID
WHERE c.ICUSTAY_ID IS NOT NULL AND i.ICUSTAY_ID IS NULL;

-- c) SUBJECT_ID not in PATIENTS
SELECT COUNT(*) AS orphan_subject
FROM CHARTEVENTS c
LEFT JOIN PATIENTS p
ON c.SUBJECT_ID = p.SUBJECT_ID
WHERE p.SUBJECT_ID IS NULL;

-- 5. Summary statistics for VALUENUM
SELECT 
    MIN(VALUENUM) AS min_value,
    MAX(VALUENUM) AS max_value,
    AVG(VALUENUM) AS avg_value,
    STDDEV(VALUENUM) AS stddev_value
FROM CHARTEVENTS
WHERE VALUENUM IS NOT NULL;

--SERVICES
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_id,
    COUNT(DISTINCT SUBJECT_ID) AS distinct_subject_id,
    COUNT(DISTINCT HADM_ID) AS distinct_hadm_id,
    COUNT(DISTINCT TRANSFERTIME) AS distinct_transfertime,
    COUNT(DISTINCT PREV_SERVICE) AS distinct_prev_service,
    COUNT(DISTINCT CURR_SERVICE) AS distinct_curr_service
FROM SERVICES;

WITH dupes AS (
    SELECT ROW_ID, COUNT(*)
    FROM GRP5_ASG.RAW.SERVICES
    GROUP BY ROW_ID
    HAVING COUNT(*) > 1
)
SELECT *
FROM GRP5_ASG.RAW.SERVICES s
WHERE EXISTS (
    SELECT 1
    FROM dupes d
    WHERE d.ROW_ID = s.ROW_ID
);
SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN SUBJECT_ID IS NULL THEN 1 ELSE 0 END) AS null_subject_id,
    SUM(CASE WHEN HADM_ID IS NULL THEN 1 ELSE 0 END) AS null_hadm_id,
    SUM(CASE WHEN TRANSFERTIME IS NULL THEN 1 ELSE 0 END) AS null_transfertime,
    SUM(CASE WHEN PREV_SERVICE IS NULL THEN 1 ELSE 0 END) AS null_prev_service,
    SUM(CASE WHEN CURR_SERVICE IS NULL THEN 1 ELSE 0 END) AS null_curr_service
FROM SERVICES;

SELECT ROW_ID, COUNT(*) AS count
FROM SERVICES
GROUP BY ROW_ID
HAVING COUNT(*) > 1;

SELECT COUNT(*) AS null_row_id
FROM SERVICES
WHERE ROW_ID IS NULL;

-- a) SUBJECT_ID not in PATIENTS
SELECT COUNT(*) AS orphan_subject
FROM SERVICES s
LEFT JOIN PATIENTS p
ON s.SUBJECT_ID = p.SUBJECT_ID
WHERE s.SUBJECT_ID IS NOT NULL AND p.SUBJECT_ID IS NULL;

-- b) HADM_ID not in ADMISSIONS
SELECT COUNT(*) AS orphan_hadm
FROM SERVICES s
LEFT JOIN ADMISSIONS a
ON s.HADM_ID = a.HADM_ID
WHERE s.HADM_ID IS NOT NULL AND a.HADM_ID IS NULL;

SELECT HADM_ID, COUNT(*) AS service_count
FROM SERVICES
GROUP BY HADM_ID
ORDER BY service_count DESC;
;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS unique_row_id,
    COUNT(DISTINCT ICD9_CODE) AS unique_icd9_code,
    COUNT(DISTINCT SHORT_TITLE) AS unique_short_title,
    COUNT(DISTINCT LONG_TITLE) AS unique_long_title
FROM DIAGNOSES;

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN ICD9_CODE IS NULL OR TRIM(ICD9_CODE) = '' THEN 1 ELSE 0 END) AS missing_icd9_code,
    SUM(CASE WHEN SHORT_TITLE IS NULL OR TRIM(SHORT_TITLE) = '' THEN 1 ELSE 0 END) AS missing_short_title,
    SUM(CASE WHEN LONG_TITLE IS NULL OR TRIM(LONG_TITLE) = '' THEN 1 ELSE 0 END) AS missing_long_title
FROM DIAGNOSES;

SELECT
    MIN(LENGTH(SHORT_TITLE)) AS min_short_len,
    MAX(LENGTH(SHORT_TITLE)) AS max_short_len,
    AVG(LENGTH(SHORT_TITLE)) AS avg_short_len,
    MIN(LENGTH(LONG_TITLE)) AS min_long_len,
    MAX(LENGTH(LONG_TITLE)) AS max_long_len,
    AVG(LENGTH(LONG_TITLE)) AS avg_long_len
FROM DIAGNOSES
WHERE SHORT_TITLE IS NOT NULL AND LONG_TITLE IS NOT NULL;

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ICD9_CODE) AS distinct_icd9_codes,
    ROUND(COUNT(*) / COUNT(DISTINCT ICD9_CODE), 2) AS avg_rows_per_code
FROM PROCEDURES;

--data profiling procedures

SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS unique_row_id,
    COUNT(DISTINCT ICD9_CODE) AS unique_icd9_code,
    COUNT(DISTINCT SHORT_TITLE) AS unique_short_title,
    COUNT(DISTINCT LONG_TITLE) AS unique_long_title
FROM PROCEDURES;

SELECT
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_row_id,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS null_icd9_code,
    SUM(CASE WHEN SHORT_TITLE IS NULL OR TRIM(SHORT_TITLE) = '' THEN 1 ELSE 0 END) AS missing_short_title,
    SUM(CASE WHEN LONG_TITLE IS NULL OR TRIM(LONG_TITLE) = '' THEN 1 ELSE 0 END) AS missing_long_title
FROM PROCEDURES;

SELECT ICD9_ID, COUNT(*) AS duplicate_count
FROM PROCEDURES
GROUP BY ICD9_ID
HAVING COUNT(*) > 1;

SELECT ICD9_CODE, COUNT(*) AS duplicate_count
FROM PROCEDURES
GROUP BY ICD9_CODE
HAVING COUNT(*) > 1;
SELECT
    MIN(LENGTH(SHORT_TITLE)) AS min_short_len,
    MAX(LENGTH(SHORT_TITLE)) AS max_short_len,
    AVG(LENGTH(SHORT_TITLE)) AS avg_short_len,
    MIN(LENGTH(LONG_TITLE)) AS min_long_len,
    MAX(LENGTH(LONG_TITLE)) AS max_long_len,
    AVG(LENGTH(LONG_TITLE)) AS avg_long_len
FROM PROCEDURES;

SELECT
    'ROW_ID' AS column_name,
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_values,
    SUM(CASE WHEN ROW_ID IS NULL THEN 1 ELSE 0 END) AS null_count
FROM PROCEDURES

UNION ALL

SELECT
    'ICD9_CODE' AS column_name,
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ICD9_CODE) AS distinct_values,
    SUM(CASE WHEN ICD9_CODE IS NULL THEN 1 ELSE 0 END) AS null_count
FROM PROCEDURES;


SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ROW_ID) AS distinct_row_id,
    COUNT(DISTINCT ICD9_CODE) AS distinct_icd9_code,
    ROUND(COUNT(DISTINCT ICD9_CODE) / COUNT(*) * 100, 2) AS icd9_uniqueness_pct,
    ROUND(COUNT(*) / COUNT(DISTINCT ICD9_CODE), 2) AS avg_rows_per_code
FROM PROCEDURES;
