--CREATE SCHEMA IF NOT EXISTS ANALYTICS;GRP5_ASG
-- Create dimension tables 
--Grain: 1 row per patient, Why DIM?: Contains descriptive attributes (gender, DOB, age) — not events, used for filtering/grouping.
CREATE OR REPLACE TABLE ANALYTICS.DIM_PATIENT AS
SELECT
    SUBJECT_ID,
    GENDER,
    DOB,
    DOD,
    EXPIRE_FLAG
FROM CLEAN.PATIENTS;
-- Grain: 1 row per ICD9 diagnosis, Why DIM?: Descriptive attributes for diagnosis; connected to FACT_DIAGNOSES.
CREATE OR REPLACE TABLE ANALYTICS.DIM_DIAGNOSIS AS
SELECT
    ICD9_CODE,
    SHORT_TITLE,
    LONG_TITLE
FROM CLEAN.DIAGNOSIS;


-- Grain: 1 row per care unit (ICU/ward), Why DIM?: Describes location/department, used for transfers, ICUs, callouts.
CREATE OR REPLACE TABLE ANALYTICS.DIM_CAREUNIT AS
SELECT DISTINCT CAREUNIT
FROM (
    SELECT FIRST_CAREUNIT AS CAREUNIT FROM CLEAN.ICUSTAYS
    UNION
    SELECT LAST_CAREUNIT FROM CLEAN.ICUSTAYS
    UNION
    SELECT PREV_CAREUNIT FROM CLEAN.TRANSFERS
    UNION
    SELECT CURR_CAREUNIT FROM CLEAN.TRANSFERS
)
WHERE CAREUNIT IS NOT NULL;




-- Grain: 1 row per service/department, Why DIM?: Describes service for analysis (e.g., Surgery, Medicine).
CREATE OR REPLACE TABLE ANALYTICS.DIM_SERVICE AS
SELECT DISTINCT
    PREV_SERVICE AS SERVICE
FROM CLEAN.SERVICES
UNION
SELECT DISTINCT CURR_SERVICE
FROM CLEAN.SERVICES;
-- Grain: 1 row per day, Why DIM?: Time dimension, used to filter and aggregate all events.
DROP TABLE IF EXISTS ANALYTICS.DIM_TIME;

CREATE OR REPLACE TABLE ANALYTICS.DIM_TIME AS
WITH calendar AS (
    SELECT
        DATEADD(day, seq4(), '2000-01-01')::DATE AS CAL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 10000))
)
SELECT
    CAL_DATE,
    YEAR(CAL_DATE)    AS YEAR,
    MONTH(CAL_DATE)   AS MONTH,
    DAY(CAL_DATE)     AS DAY,
    WEEK(CAL_DATE)    AS WEEK,
    QUARTER(CAL_DATE) AS QUARTER
FROM calendar;


--Fact tables
-- Grain: 1 row per hospital admission (HADM_ID), Why FACT?: Represents an event (admission) and has measurable metrics like LOS and mortality.
CREATE OR REPLACE TABLE ANALYTICS.FACT_ADMISSIONS AS
SELECT
    HADM_ID,
    SUBJECT_ID,
    CAST(ADMITTIME AS DATE) AS ADMIT_DATE,
    CAST(DISCHTIME AS DATE) AS DISCH_DATE,

    ADMISSION_TYPE,
    INSURANCE,
    ETHNICITY,
    HOSPITAL_EXPIRE_FLAG,

    DATEDIFF('hour', ADMITTIME, DISCHTIME)/24.0 AS HOSPITAL_LOS_DAYS
FROM CLEAN.ADMISSIONS;

--Grain: 1 row per ICU stay (ICUSTAY_ID),Why FACT?: ICU stay is an event; metrics include ICU LOS.
CREATE OR REPLACE TABLE ANALYTICS.FACT_ICU_STAYS AS
SELECT
    ICUSTAY_ID,
    HADM_ID,
    SUBJECT_ID,
    FIRST_CAREUNIT,
    LAST_CAREUNIT,
    INTIME AS ICU_INTIME,
    OUTTIME AS ICU_OUTTIME,
    LOS AS ICU_LOS_DAYS
FROM CLEAN.ICUSTAYS;
-- Grain: 1 row per transfer,Why FACT?: Patient movement is an event; metric is LOS per transfer.
CREATE OR REPLACE TABLE ANALYTICS.FACT_TRANSFERS AS
SELECT
    ROW_ID AS TRANSFER_ID,
    SUBJECT_ID,
    HADM_ID,
    ICUSTAY_ID,

    PREV_CAREUNIT,
    CURR_CAREUNIT,
    CAST(OUTTIME AS DATE) AS OUT_TIME,
    CAST(INTIME AS DATE) AS TRANSFER_DATE,
    LOS AS TRANSFER_LOS_DAYS
FROM CLEAN.TRANSFERS;

-- Grain: 1 row per callout, Why FACT?: Callout is an event; metrics: acknowledgment delay, total callout time.
CREATE OR REPLACE TABLE ANALYTICS.FACT_CALLOUTS AS
SELECT
    ROW_ID AS CALLOUT_ID,
    SUBJECT_ID,
    HADM_ID,
    CURR_CAREUNIT,
    CALLOUT_SERVICE,
    CAST(CREATETIME AS DATE) AS CALLOUT_DATE,
    DATEDIFF('minute', CREATETIME, ACKNOWLEDGETIME) AS ACK_DELAY_MIN,
    DATEDIFF('minute', CREATETIME, OUTCOMETIME) AS TOTAL_CALLOUT_MIN
FROM CLEAN.CALLOUT;


--Grain: 1 row per diagnosis code per admission, Why FACT?: Diagnosis assignment is an event, links to DIM_DIAGNOSIS.
CREATE OR REPLACE TABLE ANALYTICS.FACT_DIAGNOSES AS
SELECT
    ROW_ID AS DIAG_EVENT_ID,
    HADM_ID,
    SUBJECT_ID,
    ICD9_CODE
FROM CLEAN.DIAGNOSES_ICD;


-- Grain: 1 row per prescription, Why FACT?: Medication prescribed is an event.
CREATE OR REPLACE TABLE ANALYTICS.FACT_PRESCRIPTIONS AS
SELECT
    ROW_ID AS PRESCRIPTION_ID,
    HADM_ID,
    ICUSTAY_ID,
    DRUG,
    CAST(STARTDATE AS DATE) AS START_DATE,
    CAST(ENDDATE AS DATE) AS END_DATE,
    ROUTE,
    DOSE_VAL_RX,
    DOSE_UNIT_RX
FROM CLEAN.PRESCRIPTIONS;
DESC TABLE ANALYTICS.FACT_TRANSFERS;
MIN(TRANSFER_DATE)
MAX(TRANSFER_DATE)
SELECT DISTINCT CURR_CAREUNIT
FROM CLEAN.TRANSFERS;

SELECT
    CURR_CAREUNIT,
    COUNT(*) AS NUM_TRANSFERS,
    AVG(LOS) AS AVG_STORED_LOS,
    AVG(DATEDIFF('hour', INTIME, OUTTIME)/24.0) AS AVG_REAL_LOS
FROM CLEAN.TRANSFERS
WHERE OUTTIME IS NOT NULL
GROUP BY CURR_CAREUNIT;
CREATE OR REPLACE TABLE ANALYTICS.FACT_TRANSFERS AS
SELECT
    ROW_ID AS TRANSFER_ID,
    SUBJECT_ID,
    HADM_ID,
    ICUSTAY_ID,
    PREV_CAREUNIT,
    CURR_CAREUNIT,

    DATEDIFF('day', INTIME, OUTTIME)/24.0 AS TRANSFER_LOS_DAYS
FROM CLEAN.TRANSFERS
WHERE OUTTIME IS NOT NULL;
-- Add primary keys to make stars
ALTER TABLE ANALYTICS.DIM_PATIENT
ADD CONSTRAINT PK_DIM_PATIENT PRIMARY KEY (SUBJECT_ID);

ALTER TABLE ANALYTICS.DIM_DIAGNOSIS
ADD CONSTRAINT PK_DIM_DIAGNOSIS PRIMARY KEY (ICD9_CODE);

ALTER TABLE ANALYTICS.DIM_TIME
ADD CONSTRAINT PK_DIM_TIME PRIMARY KEY (CAL_DATE);

ALTER TABLE ANALYTICS.DIM_CAREUNIT
ADD CONSTRAINT PK_DIM_CAREUNIT PRIMARY KEY (CAREUNIT);


ALTER TABLE ANALYTICS.DIM_SERVICE
ADD CONSTRAINT PK_DIM_SERVICE PRIMARY KEY (SERVICE);

ALTER TABLE ANALYTICS.FACT_ADMISSIONS
ADD CONSTRAINT PK_FACT_ADMISSIONS PRIMARY KEY (HADM_ID);

ALTER TABLE ANALYTICS.FACT_ICU_STAYS
ADD CONSTRAINT PK_FACT_ICU PRIMARY KEY (ICUSTAY_ID);

ALTER TABLE ANALYTICS.FACT_TRANSFERS
ADD CONSTRAINT PK_FACT_TRANSFERS PRIMARY KEY (TRANSFER_ID);

ALTER TABLE ANALYTICS.FACT_CALLOUTS
ADD CONSTRAINT PK_FACT_CALLOUTS PRIMARY KEY (CALLOUT_ID);

ALTER TABLE ANALYTICS.FACT_DIAGNOSES
ADD CONSTRAINT PK_FACT_DIAGNOSES PRIMARY KEY (DIAG_EVENT_ID);

ALTER TABLE ANALYTICS.FACT_PRESCRIPTIONS
ADD CONSTRAINT PK_FACT_RX PRIMARY KEY (PRESCRIPTION_ID);

--add foreign keys to match dim to fact to create actual stars
ALTER TABLE ANALYTICS.FACT_ADMISSIONS
ADD CONSTRAINT FK_ADM_PATIENT
FOREIGN KEY (SUBJECT_ID)
REFERENCES ANALYTICS.DIM_PATIENT(SUBJECT_ID);

ALTER TABLE ANALYTICS.FACT_ADMISSIONS
ADD CONSTRAINT FK_ADM_TIME
FOREIGN KEY (ADMIT_DATE)
REFERENCES ANALYTICS.DIM_TIME(CAL_DATE);


ALTER TABLE ANALYTICS.FACT_DIAGNOSES
ADD CONSTRAINT FK_DIAG_CODE
FOREIGN KEY (ICD9_CODE)
REFERENCES ANALYTICS.DIM_DIAGNOSIS(ICD9_CODE);

ALTER TABLE ANALYTICS.FACT_DIAGNOSES
ADD CONSTRAINT FK_DIAG_PATIENT
FOREIGN KEY (SUBJECT_ID)
REFERENCES ANALYTICS.DIM_PATIENT(SUBJECT_ID);

ALTER TABLE ANALYTICS.FACT_ICU_STAYS
ADD CONSTRAINT FK_ICU_PATIENT
FOREIGN KEY (SUBJECT_ID)
REFERENCES ANALYTICS.DIM_PATIENT(SUBJECT_ID);

ALTER TABLE ANALYTICS.FACT_ICU_STAYS
ADD CONSTRAINT FK_ICU_CAREUNIT
FOREIGN KEY (FIRST_CAREUNIT)
REFERENCES ANALYTICS.DIM_CAREUNIT(CAREUNIT);

ALTER TABLE ANALYTICS.FACT_ICU_STAYS
ADD CONSTRAINT FK_ICU_TO
FOREIGN KEY (LAST_CAREUNIT)
REFERENCES ANALYTICS.DIM_CAREUNIT(CAREUNIT);


ALTER TABLE ANALYTICS.FACT_TRANSFERS
ADD CONSTRAINT FK_TRANSFER_FROM
FOREIGN KEY (PREV_CAREUNIT)
REFERENCES ANALYTICS.DIM_CAREUNIT(CAREUNIT);

ALTER TABLE ANALYTICS.FACT_TRANSFERS
ADD CONSTRAINT FK_TRANSFER_TO
FOREIGN KEY (CURR_CAREUNIT)
REFERENCES ANALYTICS.DIM_CAREUNIT(CAREUNIT);

ALTER TABLE ANALYTICS.FACT_CALLOUTS
ADD CONSTRAINT FK_CALLOUT_UNIT
FOREIGN KEY (CURR_CAREUNIT)
REFERENCES ANALYTICS.DIM_CAREUNIT(CAREUNIT);

ALTER TABLE ANALYTICS.FACT_CALLOUTS
ADD CONSTRAINT FK_CALLOUT_SERVICE
FOREIGN KEY (CALLOUT_SERVICE)
REFERENCES ANALYTICS.DIM_SERVICE(SERVICE);

ALTER TABLE ANALYTICS.FACT_CALLOUTS
ADD CONSTRAINT FK_CALLOUT_TIME
FOREIGN KEY (CALLOUT_DATE)
REFERENCES ANALYTICS.DIM_TIME(CAL_DATE);

ALTER TABLE ANALYTICS.FACT_PRESCRIPTIONS
ADD CONSTRAINT FK_RX_TIME
FOREIGN KEY (START_DATE)
REFERENCES ANALYTICS.DIM_TIME(CAL_DATE);













